### ISSUE TITLE
Swap icon names for the 2 icons attached (Car icon - Masina, Park icon - Parcare)

### ISSUE THREAD

**Issue by valigvr** [opentransportro/transit-ui#16]
![Icon Park](https://user-images.githubusercontent.com/64739281/80919073-b02fd600-8d70-11ea-8df6-9fc4f7699cd3.jpg)
![Icon Car](https://user-images.githubusercontent.com/64739281/80919074-b1610300-8d70-11ea-9159-15c1f98e628d.jpg)

**Comment by vesavlad** [comment]
fixed with a5da5fa2d039b19bd9cfcec9c16e749fe6d0454a
