### ISSUE TITLE
On Favorites tab, when the text is in RO, text with diacritics is not alligned

### ISSUE THREAD

**Issue by ShIulia** [opentransportro/transit-ui#36]
https://imghostr.com/13b60a_fbk

**Comment by vesavlad** [comment]
In my case it looks just fine, could be a browser problem
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1428537/82525915-4a4a9900-9b3b-11ea-936b-0e89a1c6eab1.png">

Please provide more details about:
 - browser, version
 - os

**Comment by vesavlad** [comment]
Since no response for some time will close this issue
