### ISSUE TITLE
Train icon is bigger than the rest

### ISSUE THREAD

**Issue by cseh17** [opentransportro/transit-ui#42]
[https://drive.google.com/file/d/1NVPRCkDSyWqB-77NhK4vTZNkv3HLG_dg/view?usp=sharing](url)

**Comment by vesavlad** [comment]
Data seems to be cached on your side:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/1428537/83377224-9ddfa100-a3dd-11ea-94bc-86aa8a1cd261.png">

@MEMOSTUDIOS can you please verify that everything is just fine

**Comment by MEMOSTUDIOS** [comment]
I don't see the train icon to be bigger.

**Comment by vesavlad** [comment]
closing issue, since also on my side the problem does not appear to be valid
