### ISSUE TITLE
When About page is closed, the page dose not use the current location but it jumps back to default

### ISSUE THREAD

**Issue by cseh17** [opentransportro/transit-ui#44]

**Comment by vesavlad** [comment]
Indeed the result of hitting back seems to be navigation to /

**Comment by vesavlad** [comment]
should be fixed with 0377561f1f109fa6741c5cfd12558c530a1aa17c

**Comment by vesavlad** [comment]
@cseh17 could you please check if fixed

**Comment by cseh17** [comment]
Location is correct now.
